---
apiVersion: v1
kind: Pod
metadata:
  name: csi-driver-s3-s3fs-test-nginx
  namespace: default
spec:
  containers:
  - name: csi-driver-s3-s3fs-test-nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /var/lib/www/html
      name: webroot
  volumes:
  - name: webroot
    persistentVolumeClaim:
      claimName: csi-driver-s3-pvc
      readOnly: false